name: Deploying Backend Server To Fly.io

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  deploy-to-fly-io:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Superfly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Run Flyctl Deploy
        run: flyctl deploy backend --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
