name: Github Actions Client Deployment To Vercel

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  deploy-client-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '23'
      
      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Build Project
        working-directory: ./frontend
        run: npm run build
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
        run: npx vercel --prod --token $VERCEL_TOKEN --yes --cwd frontend